package com.example.MyBookShopApp.data;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;
import java.util.Arrays;
import java.util.List;

@Entity
@Table(name = "authors", indexes = {@Index(name = "authors_slug", columnList = "slug", unique = true)})
@Data
@ApiModel(description = "data model of author entity")
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db", position = 1)
    private int id;
    @ApiModelProperty(position = 5)
    private String photo;
    @Column(nullable = false)
    @ApiModelProperty(position = 3)
    private String slug;
    @Column(nullable = false)
    @ApiModelProperty(value = "authors full name", example = "Rush, Jason C.", position = 2)
    private String name;
    @Column(columnDefinition = "TEXT")
    @ApiModelProperty(position = 4)
    private String description;
    @ManyToMany
    @JoinTable(name = "book2author", joinColumns = @JoinColumn(name = "author_id"), inverseJoinColumns = @JoinColumn(name = "book_id"))
    @JsonIgnore
    private List<Book> bookList;

    @Override
    public String toString() {
        return "Author{" +
                "id=" + id +
//                ", photo='" + photo + '\'' +
//                ", slug='" + slug + '\'' +
                ", name='" + name + '\'' +
//                ", description='" + description + '\'' +
                ", bookList=" + Arrays.toString(bookList.stream().map(Book::getTitle).toArray()) +
                '}';
    }
}
