DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

CREATE TABLE  books(
    id INT AUTO_INCREMENT PRIMARY KEY,
    author_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    priceOld  VARCHAR(255) DEFAULT NULL,
    price VARCHAR(255) DEFAULT NULL
);

CREATE TABLE authors (
    id INT AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);