package com.example.MyBookShopApp.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Builder;
import lombok.Getter;

import java.util.List;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL;

@Builder
@Getter
@ApiModel(description = "data model of author entity")
@JsonInclude(NON_NULL)
public class AuthorDto {

    @ApiModelProperty(value = "author id generated by db")
    private int id;
    @ApiModelProperty(value = "path to author's photo")
    private String photo;
    @ApiModelProperty(value = "mnemonic identity sequence of characters")
    private String slug;
    @ApiModelProperty(value = "authors full name", example = "Rush, Jason C.")
    private String name;
    @JsonIgnore
    private String description;
    @JsonIgnore
    private List<BookDto> bookList;
}
